#common constants
CELL_SIZE = 80
WIDTH = CELL_SIZE * 8
HEIGHT = CELL_SIZE * 8
FPS = 30

PATH_TO_SESSIONS_FILE = "checkers_sessions.txt"
PATH_TO_MEDIA = "media/"
#common constansts

#COLORS
BLACK = (0, 0, 0)
ALMOST_BLACK = (32, 32, 32)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
BLACK_GREEN = (0, 153, 0)
BLUE = (0, 0, 255)
GREY = (128, 128, 128)
YELLOW = (255, 255, 0)

TRANSPARENT = (-1, -1, -1)

WHITE_CELL = WHITE[:]
BLACK_CELL = GREY[:]
HIGHLIGHTED_CELL = BLACK_GREEN[:]
SELECTED_CELL = BLUE[:]

WHITE_CHECKER = WHITE[:]
BLACK_CHECKER = ALMOST_BLACK[:]
KING_CROWN_COLOR = YELLOW[:]

DEFAULT_CLEAR_SCREEN = ALMOST_BLACK[:]
#COLORS

#OTHER
DEFAULT_FONT = None
DEFAULT_FONT_SIZE = CELL_SIZE * 500 // 800
#OTHER

#CHECKERS_INFO
DEFAULT_SELECTED_CHECKER = (-1, -1)

NO_CHECKER = (-1, -1, -1)

CHECKER_SIZE = CELL_SIZE / 16 * 5
CHECKER_SELECTED_SIZE = CELL_SIZE / 16 * 6
CHECKER_KING_SIZE = CELL_SIZE / 16 * 1
CHECKER_SELECTED_KOEF = 1.2
#CHECKERS_INFO
